// 104 matches: 72 group stage + 16 round of 32 + 8 round of 16 + 4 QF + 2 SF + 1 third place + 1 final.
//
// Slot conventions (used for KO matches before teams are known):
//   "1A"      → winner of group A
//   "2A"      → runner-up of group A
//   "3A/B/F"  → best 3rd-placed of groups A, B, F (slash-separated)
//   "W73"     → winner of match #73
//   "L101"    → loser of match #101 (third place playoff)
//
// For GROUP-phase matches: provide `groupName`, `homeTeamCode`, `awayTeamCode`.
// For KO-phase matches: provide either team codes (if already known) or slot strings.
//
// `kickoffAt` is an ISO 8601 datetime string in UTC, e.g. "2026-06-11T20:00:00Z".

export type MatchPhase =
  | 'GROUP'
  | 'ROUND_OF_32'
  | 'ROUND_OF_16'
  | 'QUARTER_FINAL'
  | 'SEMI_FINAL'
  | 'THIRD_PLACE'
  | 'FINAL';

export type MatchSeed = {
  /** Unique match number, 1..104 (FIFA-style) */
  matchNumber: number;
  phase: MatchPhase;
  /** Group letter, required for GROUP phase only */
  groupName?: string;
  /** Known home team — required for GROUP, optional for KO */
  homeTeamCode?: string;
  /** Known away team — required for GROUP, optional for KO */
  awayTeamCode?: string;
  /** Bracket placeholder when team is not yet known (KO only) */
  homeSlot?: string;
  /** Bracket placeholder when team is not yet known (KO only) */
  awaySlot?: string;
  /** ISO 8601 UTC, e.g. "2026-06-11T20:00:00Z" */
  kickoffAt: string;
  stadium: string;
  city: string;
  referee?: string;
};

export const matches: MatchSeed[] = [
  // Example — group match
  {
    matchNumber: 1,
    phase: 'GROUP',
    groupName: 'A',
    homeTeamCode: 'MEX',
    awayTeamCode: 'RSA',
    kickoffAt: '2026-06-11T13:00:00Z',
    stadium: 'Stade de Mexico',
    city: 'Mexico',
  },
  {
    matchNumber: 2,
    phase: 'GROUP',
    groupName: 'A',
    homeTeamCode: 'KOR',
    awayTeamCode: 'CZE',
    kickoffAt: '2026-06-11T20:00:00Z',
    stadium: 'Stade de Guadalajara',
    city: 'Guadalajara',
  },
  {
    matchNumber: 3,
    phase: 'GROUP',
    groupName: 'B',
    homeTeamCode: 'CAN',
    awayTeamCode: 'BIH',
    kickoffAt: '2026-06-12T13:00:00Z',
    stadium: 'Stade de Toronto',
    city: 'Toronto',
  },
  {
    matchNumber: 4,
    phase: 'GROUP',
    groupName: 'D',
    homeTeamCode: 'USA',
    awayTeamCode: 'PAR',
    kickoffAt: '2026-06-12T19:00:00Z',
    stadium: 'Stade de Los Angeles',
    city: 'Los Angeles',
  },
  {
    matchNumber: 5,
    phase: 'GROUP',
    groupName: 'B',
    homeTeamCode: 'QAT',
    awayTeamCode: 'SUI',
    kickoffAt: '2026-06-13T13:00:00Z',
    stadium: 'Stade de la baie de San Francisco',
    city: 'San Francisco',
  },
  {
    matchNumber: 6,
    phase: 'GROUP',
    groupName: 'C',
    homeTeamCode: 'BRA',
    awayTeamCode: 'MAR',
    kickoffAt: '2026-06-13T16:00:00Z',
    stadium: 'Stade de New York New Jersey',
    city: 'New York',
  },
  {
    matchNumber: 7,
    phase: 'GROUP',
    groupName: 'C',
    homeTeamCode: 'HTI',
    awayTeamCode: 'SCO',
    kickoffAt: '2026-06-13T19:00:00Z',
    stadium: 'Stade de Boston',
    city: 'Boston',
  },
  {
    matchNumber: 8,
    phase: 'GROUP',
    groupName: 'D',
    homeTeamCode: 'AUS',
    awayTeamCode: 'TUR',
    kickoffAt: '2026-06-13T22:00:00Z',
    stadium: 'BC Place de Vancouver',
    city: 'Vancouver',
  },
  {
    matchNumber: 9,
    phase: 'GROUP',
    groupName: 'E',
    homeTeamCode: 'GER',
    awayTeamCode: 'CUW',
    kickoffAt: '2026-06-14T11:00:00Z',
    stadium: 'Stade de Houston',
    city: 'Houston',
  },
  {
    matchNumber: 10,
    phase: 'GROUP',
    groupName: 'F',
    homeTeamCode: 'NED',
    awayTeamCode: 'JPN',
    kickoffAt: '2026-06-14T14:00:00Z',
    stadium: 'Stade de Dallas',
    city: 'Dallas',
  },
  {
    matchNumber: 11,
    phase: 'GROUP',
    groupName: 'E',
    homeTeamCode: 'CIV',
    awayTeamCode: 'ECU',
    kickoffAt: '2026-06-14T17:00:00Z',
    stadium: 'Stade de Philadelphie',
    city: 'Philadelphie',
  },
  {
    matchNumber: 12,
    phase: 'GROUP',
    groupName: 'F',
    homeTeamCode: 'SWE',
    awayTeamCode: 'TUN',
    kickoffAt: '2026-06-14T20:00:00Z',
    stadium: 'Stade de Monterrey',
    city: 'Monterrey',
  },
  {
    matchNumber: 13,
    phase: 'GROUP',
    groupName: 'H',
    homeTeamCode: 'ESP',
    awayTeamCode: 'CPV',
    kickoffAt: '2026-06-15T10:00:00Z',
    stadium: "Stade d'Atlanta",
    city: 'Atlanta',
  },
  {
    matchNumber: 14,
    phase: 'GROUP',
    groupName: 'G',
    homeTeamCode: 'BEL',
    awayTeamCode: 'EGY',
    kickoffAt: '2026-06-15T13:00:00Z',
    stadium: 'Stade de Seattle',
    city: 'Seattle',
  },
  {
    matchNumber: 15,
    phase: 'GROUP',
    groupName: 'H',
    homeTeamCode: 'KSA',
    awayTeamCode: 'URU',
    kickoffAt: '2026-06-15T16:00:00Z',
    stadium: 'Stade de Miami',
    city: 'Miami',
  },
  {
    matchNumber: 16,
    phase: 'GROUP',
    groupName: 'G',
    homeTeamCode: 'IRI',
    awayTeamCode: 'NZL',
    kickoffAt: '2026-06-15T19:00:00Z',
    stadium: 'Stade de Los Angeles',
    city: 'Los Angeles',
  },
  {
    matchNumber: 17,
    phase: 'GROUP',
    groupName: 'I',
    homeTeamCode: 'FRA',
    awayTeamCode: 'SEN',
    kickoffAt: '2026-06-16T13:00:00Z',
    stadium: 'Stade de New York New Jersey',
    city: 'New York',
  },
  {
    matchNumber: 18,
    phase: 'GROUP',
    groupName: 'I',
    homeTeamCode: 'IRQ',
    awayTeamCode: 'NOR',
    kickoffAt: '2026-06-16T16:00:00Z',
    stadium: 'Stade de Boston',
    city: 'Boston',
  },
  {
    matchNumber: 19,
    phase: 'GROUP',
    groupName: 'J',
    homeTeamCode: 'ARG',
    awayTeamCode: 'ALG',
    kickoffAt: '2026-06-16T19:00:00Z',
    stadium: 'Stade de Kansas City',
    city: 'Kansas City',
  },
  {
    matchNumber: 20,
    phase: 'GROUP',
    groupName: 'J',
    homeTeamCode: 'AUT',
    awayTeamCode: 'JOR',
    kickoffAt: '2026-06-16T22:00:00Z',
    stadium: 'Stade de la baie de San Francisco',
    city: 'San Francisco',
  },
  {
    matchNumber: 21,
    phase: 'GROUP',
    groupName: 'K',
    homeTeamCode: 'POR',
    awayTeamCode: 'COD',
    kickoffAt: '2026-06-17T11:00:00Z',
    stadium: 'Stade de Houston',
    city: 'Houston',
  },
  {
    matchNumber: 22,
    phase: 'GROUP',
    groupName: 'L',
    homeTeamCode: 'ENG',
    awayTeamCode: 'CRO',
    kickoffAt: '2026-06-17T14:00:00Z',
    stadium: 'Stade de Dallas',
    city: 'Dallas',
  },
  {
    matchNumber: 23,
    phase: 'GROUP',
    groupName: 'L',
    homeTeamCode: 'GHA',
    awayTeamCode: 'PAN',
    kickoffAt: '2026-06-17T17:00:00Z',
    stadium: 'Stade de Toronto',
    city: 'Toronto',
  },
  {
    matchNumber: 24,
    phase: 'GROUP',
    groupName: 'K',
    homeTeamCode: 'UZB',
    awayTeamCode: 'COL',
    kickoffAt: '2026-06-17T20:00:00Z',
    stadium: 'Stade de Mexico',
    city: 'Mexico',
  },
  {
    matchNumber: 25,
    phase: 'GROUP',
    groupName: 'A',
    homeTeamCode: 'CZE',
    awayTeamCode: 'RSA',
    kickoffAt: '2026-06-18T10:00:00Z',
    stadium: "Stade d'Atlanta",
    city: 'Atlanta',
  },
  {
    matchNumber: 26,
    phase: 'GROUP',
    groupName: 'B',
    homeTeamCode: 'SUI',
    awayTeamCode: 'BIH',
    kickoffAt: '2026-06-18T13:00:00Z',
    stadium: 'Stade de Los Angeles',
    city: 'Los Angeles',
  },
  {
    matchNumber: 27,
    phase: 'GROUP',
    groupName: 'B',
    homeTeamCode: 'CAN',
    awayTeamCode: 'QAT',
    kickoffAt: '2026-06-18T16:00:00Z',
    stadium: 'BC Place de Vancouver',
    city: 'Vancouver',
  },
  {
    matchNumber: 28,
    phase: 'GROUP',
    groupName: 'A',
    homeTeamCode: 'MEX',
    awayTeamCode: 'KOR',
    kickoffAt: '2026-06-18T19:00:00Z',
    stadium: 'Stade de Guadalajara',
    city: 'Guadalajara',
  },
  {
    matchNumber: 29,
    phase: 'GROUP',
    groupName: 'D',
    homeTeamCode: 'USA',
    awayTeamCode: 'AUS',
    kickoffAt: '2026-06-19T13:00:00Z',
    stadium: 'Stade de Seattle',
    city: 'Seattle',
  },
  {
    matchNumber: 30,
    phase: 'GROUP',
    groupName: 'C',
    homeTeamCode: 'SCO',
    awayTeamCode: 'MAR',
    kickoffAt: '2026-06-19T16:00:00Z',
    stadium: 'Stade de Boston',
    city: 'Boston',
  },
  {
    matchNumber: 31,
    phase: 'GROUP',
    groupName: 'C',
    homeTeamCode: 'BRA',
    awayTeamCode: 'HTI',
    kickoffAt: '2026-06-19T18:30:00Z',
    stadium: 'Stade de Philadelphie',
    city: 'Philadelphie',
  },
  {
    matchNumber: 32,
    phase: 'GROUP',
    groupName: 'D',
    homeTeamCode: 'TUR',
    awayTeamCode: 'PAR',
    kickoffAt: '2026-06-19T21:00:00Z',
    stadium: 'Stade de la baie de San Francisco',
    city: 'San Francisco',
  },
  {
    matchNumber: 33,
    phase: 'GROUP',
    groupName: 'F',
    homeTeamCode: 'NED',
    awayTeamCode: 'SWE',
    kickoffAt: '2026-06-20T11:00:00Z',
    stadium: 'Stade de Houston',
    city: 'Houston',
  },
  {
    matchNumber: 34,
    phase: 'GROUP',
    groupName: 'E',
    homeTeamCode: 'GER',
    awayTeamCode: 'CIV',
    kickoffAt: '2026-06-20T14:00:00Z',
    stadium: 'Stade de Toronto',
    city: 'Toronto',
  },
  {
    matchNumber: 35,
    phase: 'GROUP',
    groupName: 'E',
    homeTeamCode: 'ECU',
    awayTeamCode: 'CUW',
    kickoffAt: '2026-06-20T18:00:00Z',
    stadium: 'Stade de Kansas City',
    city: 'Kansas City',
  },
  {
    matchNumber: 36,
    phase: 'GROUP',
    groupName: 'F',
    homeTeamCode: 'TUN',
    awayTeamCode: 'JPN',
    kickoffAt: '2026-06-20T22:00:00Z',
    stadium: 'Stade de Monterrey',
    city: 'Monterrey',
  },
  {
    matchNumber: 37,
    phase: 'GROUP',
    groupName: 'H',
    homeTeamCode: 'ESP',
    awayTeamCode: 'KSA',
    kickoffAt: '2026-06-21T10:00:00Z',
    stadium: "Stade d'Atlanta",
    city: 'Atlanta',
  },
  {
    matchNumber: 38,
    phase: 'GROUP',
    groupName: 'G',
    homeTeamCode: 'BEL',
    awayTeamCode: 'IRI',
    kickoffAt: '2026-06-21T13:00:00Z',
    stadium: 'Stade de Los Angeles',
    city: 'Los Angeles',
  },
  {
    matchNumber: 39,
    phase: 'GROUP',
    groupName: 'H',
    homeTeamCode: 'CPV',
    awayTeamCode: 'URU',
    kickoffAt: '2026-06-21T16:00:00Z',
    stadium: 'Stade de Miami',
    city: 'Miami',
  },
  {
    matchNumber: 40,
    phase: 'GROUP',
    groupName: 'G',
    homeTeamCode: 'NZL',
    awayTeamCode: 'EGY',
    kickoffAt: '2026-06-21T19:00:00Z',
    stadium: 'BC Place de Vancouver',
    city: 'Vancouver',
  },
  {
    matchNumber: 41,
    phase: 'GROUP',
    groupName: 'J',
    homeTeamCode: 'ARG',
    awayTeamCode: 'AUT',
    kickoffAt: '2026-06-22T11:00:00Z',
    stadium: 'Stade de Dallas',
    city: 'Dallas',
  },
  {
    matchNumber: 42,
    phase: 'GROUP',
    groupName: 'I',
    homeTeamCode: 'FRA',
    awayTeamCode: 'IRQ',
    kickoffAt: '2026-06-22T15:00:00Z',
    stadium: 'Stade de Philadelphie',
    city: 'Philadelphie',
  },
  {
    matchNumber: 43,
    phase: 'GROUP',
    groupName: 'I',
    homeTeamCode: 'NOR',
    awayTeamCode: 'SEN',
    kickoffAt: '2026-06-22T18:00:00Z',
    stadium: 'Stade de New York New Jersey',
    city: 'New York',
  },
  {
    matchNumber: 44,
    phase: 'GROUP',
    groupName: 'J',
    homeTeamCode: 'JOR',
    awayTeamCode: 'ALG',
    kickoffAt: '2026-06-22T21:00:00Z',
    stadium: 'Stade de la baie de San Francisco',
    city: 'San Francisco',
  },
  {
    matchNumber: 45,
    phase: 'GROUP',
    groupName: 'K',
    homeTeamCode: 'POR',
    awayTeamCode: 'UZB',
    kickoffAt: '2026-06-23T11:00:00Z',
    stadium: 'Stade de Houston',
    city: 'Houston',
  },
  {
    matchNumber: 46,
    phase: 'GROUP',
    groupName: 'L',
    homeTeamCode: 'ENG',
    awayTeamCode: 'GHA',
    kickoffAt: '2026-06-23T14:00:00Z',
    stadium: 'Stade de Boston',
    city: 'Boston',
  },
  {
    matchNumber: 47,
    phase: 'GROUP',
    groupName: 'L',
    homeTeamCode: 'PAN',
    awayTeamCode: 'CRO',
    kickoffAt: '2026-06-23T17:00:00Z',
    stadium: 'Stade de Toronto',
    city: 'Toronto',
  },
  {
    matchNumber: 48,
    phase: 'GROUP',
    groupName: 'K',
    homeTeamCode: 'COL',
    awayTeamCode: 'COD',
    kickoffAt: '2026-06-23T20:00:00Z',
    stadium: 'Stade de Guadalajara',
    city: 'Guadalajara',
  },
  {
    matchNumber: 49,
    phase: 'GROUP',
    groupName: 'B',
    homeTeamCode: 'SUI',
    awayTeamCode: 'CAN',
    kickoffAt: '2026-06-24T13:00:00Z',
    stadium: 'BC Place de Vancouver',
    city: 'Vancouver',
  },
  {
    matchNumber: 50,
    phase: 'GROUP',
    groupName: 'B',
    homeTeamCode: 'BIH',
    awayTeamCode: 'QAT',
    kickoffAt: '2026-06-24T13:00:00Z',
    stadium: 'Stade de Seattle',
    city: 'Seattle',
  },
  {
    matchNumber: 51,
    phase: 'GROUP',
    groupName: 'C',
    homeTeamCode: 'SCO',
    awayTeamCode: 'BRA',
    kickoffAt: '2026-06-24T16:00:00Z',
    stadium: 'Stade de Miami',
    city: 'Miami',
  },
  {
    matchNumber: 52,
    phase: 'GROUP',
    groupName: 'C',
    homeTeamCode: 'MAR',
    awayTeamCode: 'HTI',
    kickoffAt: '2026-06-24T16:00:00Z',
    stadium: "Stade d'Atlanta",
    city: 'Atlanta',
  },
  {
    matchNumber: 53,
    phase: 'GROUP',
    groupName: 'A',
    homeTeamCode: 'CZE',
    awayTeamCode: 'MEX',
    kickoffAt: '2026-06-24T19:00:00Z',
    stadium: 'Stade de Mexico',
    city: 'Mexico',
  },
  {
    matchNumber: 54,
    phase: 'GROUP',
    groupName: 'A',
    homeTeamCode: 'RSA',
    awayTeamCode: 'KOR',
    kickoffAt: '2026-06-24T19:00:00Z',
    stadium: 'Stade de Monterrey',
    city: 'Monterrey',
  },
  {
    matchNumber: 55,
    phase: 'GROUP',
    groupName: 'E',
    homeTeamCode: 'ECU',
    awayTeamCode: 'GER',
    kickoffAt: '2026-06-25T14:00:00Z',
    stadium: 'Stade de New York New Jersey',
    city: 'New York',
  },
  {
    matchNumber: 56,
    phase: 'GROUP',
    groupName: 'E',
    homeTeamCode: 'CUW',
    awayTeamCode: 'CIV',
    kickoffAt: '2026-06-25T14:00:00Z',
    stadium: 'Stade de Philadelphie',
    city: 'Philadelphie',
  },
  {
    matchNumber: 57,
    phase: 'GROUP',
    groupName: 'F',
    homeTeamCode: 'TUN',
    awayTeamCode: 'NED',
    kickoffAt: '2026-06-25T17:00:00Z',
    stadium: 'Stade de Kansas City',
    city: 'Kansas City',
  },
  {
    matchNumber: 58,
    phase: 'GROUP',
    groupName: 'F',
    homeTeamCode: 'JPN',
    awayTeamCode: 'SWE',
    kickoffAt: '2026-06-25T17:00:00Z',
    stadium: 'Stade de Dallas',
    city: 'Dallas',
  },
  {
    matchNumber: 59,
    phase: 'GROUP',
    groupName: 'D',
    homeTeamCode: 'TUR',
    awayTeamCode: 'USA',
    kickoffAt: '2026-06-25T20:00:00Z',
    stadium: 'Stade de Los Angeles',
    city: 'Los Angeles',
  },
  {
    matchNumber: 60,
    phase: 'GROUP',
    groupName: 'D',
    homeTeamCode: 'PAR',
    awayTeamCode: 'AUS',
    kickoffAt: '2026-06-25T20:00:00Z',
    stadium: 'Stade de la baie de San Francisco',
    city: 'San Francisco',
  },
  {
    matchNumber: 61,
    phase: 'GROUP',
    groupName: 'I',
    homeTeamCode: 'NOR',
    awayTeamCode: 'FRA',
    kickoffAt: '2026-06-26T13:00:00Z',
    stadium: 'Stade de Boston',
    city: 'Boston',
  },
  {
    matchNumber: 62,
    phase: 'GROUP',
    groupName: 'I',
    homeTeamCode: 'SEN',
    awayTeamCode: 'IRQ',
    kickoffAt: '2026-06-26T13:00:00Z',
    stadium: 'Stade de Toronto',
    city: 'Toronto',
  },
  {
    matchNumber: 63,
    phase: 'GROUP',
    groupName: 'H',
    homeTeamCode: 'URU',
    awayTeamCode: 'ESP',
    kickoffAt: '2026-06-26T18:00:00Z',
    stadium: 'Stade de Guadalajara',
    city: 'Guadalajara',
  },
  {
    matchNumber: 64,
    phase: 'GROUP',
    groupName: 'H',
    homeTeamCode: 'CPV',
    awayTeamCode: 'KSA',
    kickoffAt: '2026-06-26T18:00:00Z',
    stadium: 'Stade de Houston',
    city: 'Houston',
  },
  {
    matchNumber: 65,
    phase: 'GROUP',
    groupName: 'G',
    homeTeamCode: 'NZL',
    awayTeamCode: 'BEL',
    kickoffAt: '2026-06-26T21:00:00Z',
    stadium: 'BC Place de Vancouver',
    city: 'Vancouver',
  },
  {
    matchNumber: 66,
    phase: 'GROUP',
    groupName: 'G',
    homeTeamCode: 'EGY',
    awayTeamCode: 'IRI',
    kickoffAt: '2026-06-26T21:00:00Z',
    stadium: 'Stade de Seattle',
    city: 'Seattle',
  },
  {
    matchNumber: 67,
    phase: 'GROUP',
    groupName: 'L',
    homeTeamCode: 'PAN',
    awayTeamCode: 'ENG',
    kickoffAt: '2026-06-27T15:00:00Z',
    stadium: 'Stade de New York New Jersey',
    city: 'New York',
  },
  {
    matchNumber: 68,
    phase: 'GROUP',
    groupName: 'L',
    homeTeamCode: 'CRO',
    awayTeamCode: 'GHA',
    kickoffAt: '2026-06-27T15:00:00Z',
    stadium: 'Stade de Philadelphie',
    city: 'Philadelphie',
  },
  {
    matchNumber: 69,
    phase: 'GROUP',
    groupName: 'K',
    homeTeamCode: 'COL',
    awayTeamCode: 'POR',
    kickoffAt: '2026-06-27T17:30:00Z',
    stadium: 'Stade de Miami',
    city: 'Miami',
  },
  {
    matchNumber: 70,
    phase: 'GROUP',
    groupName: 'K',
    homeTeamCode: 'COD',
    awayTeamCode: 'UZB',
    kickoffAt: '2026-06-27T17:30:00Z',
    stadium: "Stade d'Atlanta",
    city: 'Atlanta',
  },
  {
    matchNumber: 71,
    phase: 'GROUP',
    groupName: 'J',
    homeTeamCode: 'JOR',
    awayTeamCode: 'ARG',
    kickoffAt: '2026-06-27T20:00:00Z',
    stadium: 'Stade de Dallas',
    city: 'Dallas',
  },
  {
    matchNumber: 72,
    phase: 'GROUP',
    groupName: 'J',
    homeTeamCode: 'ALG',
    awayTeamCode: 'AUT',
    kickoffAt: '2026-06-27T20:00:00Z',
    stadium: 'Stade de Kansas City',
    city: 'Kansas City',
  },
  //
  // Example — KO match with slot placeholders
  // {
  //   matchNumber: 73,
  //   phase: "ROUND_OF_32",
  //   homeSlot: "1A",
  //   awaySlot: "3C/E/F",
  //   kickoffAt: "2026-06-28T20:00:00Z",
  //   stadium: "MetLife Stadium",
  //   city: "New York/New Jersey",
  // },
];
